from .models import RouteType

class GradeSystem():
    FRENCH = 1
    FONT = 2
    UIAA = 4
    B = 8
    V = 16
    YOSEMITE = 32

    GRADE_SYSTEM_NAMES = {
        FRENCH: "French",
        FONT: "Font Bouldering",
        UIAA: "UIAA",
        B: "Peak Bouldering",
        V: "V Grade",
        YOSEMITE: "YDS",
    }

    GRADE_SYSTEM_LIST = [
        { 'routeType': RouteType.BOULDER, 'gradeSystems': [
                { 'id': FONT, 'name': GRADE_SYSTEM_NAMES[FONT] },
                { 'id': B, 'name': GRADE_SYSTEM_NAMES[B] },
                { 'id': V, 'name': GRADE_SYSTEM_NAMES[V] },
            ] },
        { 'routeType': RouteType.SPORT, 'gradeSystems': [
                { 'id': FRENCH, 'name': GRADE_SYSTEM_NAMES[FRENCH] },
                { 'id': UIAA, 'name': GRADE_SYSTEM_NAMES[UIAA] },
                { 'id': YOSEMITE, 'name': GRADE_SYSTEM_NAMES[YOSEMITE] }
            ] },
        { 'routeType': RouteType.TRAD, 'gradeSystems': [
                { 'id': FRENCH, 'name': GRADE_SYSTEM_NAMES[FRENCH] },
                { 'id': UIAA, 'name': GRADE_SYSTEM_NAMES[UIAA] },
                { 'id': YOSEMITE, 'name': GRADE_SYSTEM_NAMES[YOSEMITE] }
            ] },
    ]


class Grade:

    GRADE_LIST = {
        GradeSystem.FRENCH: [
            { 'value': 20, 'name': '3a', 'type': GradeSystem.FRENCH },
            { 'value': 25, 'name': '3a+', 'type': GradeSystem.FRENCH },
            { 'value': 30, 'name': '3b', 'type': GradeSystem.FRENCH },
            { 'value': 35, 'name': '3b+', 'type': GradeSystem.FRENCH },
            { 'value': 40, 'name': '3c', 'type': GradeSystem.FRENCH },
            { 'value': 45, 'name': '3c+', 'type': GradeSystem.FRENCH },
            { 'value': 50, 'name': '4a', 'type': GradeSystem.FRENCH },
            { 'value': 55, 'name': '4a+', 'type': GradeSystem.FRENCH },
            { 'value': 60, 'name': '4b', 'type': GradeSystem.FRENCH },
            { 'value': 65, 'name': '4b+', 'type': GradeSystem.FRENCH },
            { 'value': 70, 'name': '4c', 'type': GradeSystem.FRENCH },
            { 'value': 75, 'name': '4c+', 'type': GradeSystem.FRENCH },
            { 'value': 80, 'name': '5a', 'type': GradeSystem.FRENCH },
            { 'value': 85, 'name': '5a+', 'type': GradeSystem.FRENCH },
            { 'value': 90, 'name': '5b', 'type': GradeSystem.FRENCH },
            { 'value': 95, 'name': '5b+', 'type': GradeSystem.FRENCH },
            { 'value': 100, 'name': '5c', 'type': GradeSystem.FRENCH },
            { 'value': 105, 'name': '5c+', 'type': GradeSystem.FRENCH },
            { 'value': 110, 'name': '6a', 'type': GradeSystem.FRENCH },
            { 'value': 115, 'name': '6a+', 'type': GradeSystem.FRENCH },
            { 'value': 120, 'name': '6b', 'type': GradeSystem.FRENCH },
            { 'value': 125, 'name': '6b+', 'type': GradeSystem.FRENCH },
            { 'value': 130, 'name': '6c', 'type': GradeSystem.FRENCH },
            { 'value': 135, 'name': '6c+', 'type': GradeSystem.FRENCH },
            { 'value': 140, 'name': '7a', 'type': GradeSystem.FRENCH },
            { 'value': 145, 'name': '7a+', 'type': GradeSystem.FRENCH },
            { 'value': 150, 'name': '7b', 'type': GradeSystem.FRENCH },
            { 'value': 155, 'name': '7b+', 'type': GradeSystem.FRENCH },
            { 'value': 160, 'name': '7c', 'type': GradeSystem.FRENCH },
            { 'value': 165, 'name': '7c+', 'type': GradeSystem.FRENCH },
            { 'value': 170, 'name': '8a', 'type': GradeSystem.FRENCH },
            { 'value': 175, 'name': '8a+', 'type': GradeSystem.FRENCH },
            { 'value': 180, 'name': '8b', 'type': GradeSystem.FRENCH },
            { 'value': 185, 'name': '8b+', 'type': GradeSystem.FRENCH },
            { 'value': 190, 'name': '8c', 'type': GradeSystem.FRENCH },
            { 'value': 192, 'name': '8c/+', 'type': GradeSystem.FRENCH },
            { 'value': 195, 'name': '8c+', 'type': GradeSystem.FRENCH },
            { 'value': 197, 'name': '8c+/9a', 'type': GradeSystem.FRENCH },
            { 'value': 200, 'name': '9a', 'type': GradeSystem.FRENCH },
            { 'value': 205, 'name': '9a+', 'type': GradeSystem.FRENCH },
            { 'value': 210, 'name': '9b', 'type': GradeSystem.FRENCH },
            { 'value': 215, 'name': '9b+', 'type': GradeSystem.FRENCH },
            { 'value': 220, 'name': '9c', 'type': GradeSystem.FRENCH },
            { 'value': 225, 'name': '9c+', 'type': GradeSystem.FRENCH },
        ],
        GradeSystem.FONT: [
            { 'value': 20, 'name': '3', 'type': GradeSystem.FONT },
            { 'value': 25, 'name': '4-', 'type': GradeSystem.FONT },
            { 'value': 30, 'name': '4', 'type': GradeSystem.FONT },
            { 'value': 35, 'name': '4+', 'type': GradeSystem.FONT },
            { 'value': 40, 'name': '5-', 'type': GradeSystem.FONT },
            { 'value': 45, 'name': '5', 'type': GradeSystem.FONT },
            { 'value': 50, 'name': '5+', 'type': GradeSystem.FONT },
            { 'value': 55, 'name': '6A', 'type': GradeSystem.FONT },
            { 'value': 60, 'name': '6A+', 'type': GradeSystem.FONT },
            { 'value': 65, 'name': '6B', 'type': GradeSystem.FONT },
            { 'value': 70, 'name': '6B+', 'type': GradeSystem.FONT },
            { 'value': 75, 'name': '6C', 'type': GradeSystem.FONT },
            { 'value': 80, 'name': '6C+', 'type': GradeSystem.FONT },
            { 'value': 85, 'name': '7A', 'type': GradeSystem.FONT },
            { 'value': 90, 'name': '7A+', 'type': GradeSystem.FONT },
            { 'value': 95, 'name': '7B', 'type': GradeSystem.FONT },
            { 'value': 100, 'name': '7B+', 'type': GradeSystem.FONT },
            { 'value': 105, 'name': '7C', 'type': GradeSystem.FONT },
            { 'value': 110, 'name': '7C+', 'type': GradeSystem.FONT },
            { 'value': 115, 'name': '8A', 'type': GradeSystem.FONT },
            { 'value': 120, 'name': '8A+', 'type': GradeSystem.FONT },
            { 'value': 125, 'name': '8B', 'type': GradeSystem.FONT },
            { 'value': 130, 'name': '8B+', 'type': GradeSystem.FONT },
            { 'value': 135, 'name': '8C', 'type': GradeSystem.FONT },
            { 'value': 140, 'name': '8C+', 'type': GradeSystem.FONT },
            { 'value': 145, 'name': '9A', 'type': GradeSystem.FONT },
        ],
        GradeSystem.UIAA: [
            { 'value': 20, 'name': '3-', 'type': GradeSystem.UIAA },
            { 'value': 30, 'name': '3', 'type': GradeSystem.UIAA },
            { 'value': 40, 'name': '3+', 'type': GradeSystem.UIAA },
            { 'value': 50, 'name': '4-', 'type': GradeSystem.UIAA },
            { 'value': 60, 'name': '4', 'type': GradeSystem.UIAA },
            { 'value': 70, 'name': '4+', 'type': GradeSystem.UIAA },
            { 'value': 80, 'name': '5-', 'type': GradeSystem.UIAA },
            { 'value': 85, 'name': '5', 'type': GradeSystem.UIAA },
            { 'value': 90, 'name': '5+', 'type': GradeSystem.UIAA },
            { 'value': 95, 'name': '5+/6-', 'type': GradeSystem.UIAA },
            { 'value': 100, 'name': '6-', 'type': GradeSystem.UIAA },
            { 'value': 105, 'name': '6', 'type': GradeSystem.UIAA },
            { 'value': 110, 'name': '6+', 'type': GradeSystem.UIAA },
            { 'value': 115, 'name': '6+/7-', 'type': GradeSystem.UIAA },
            { 'value': 117, 'name': '7-', 'type': GradeSystem.UIAA },
            { 'value': 120, 'name': '7', 'type': GradeSystem.UIAA },
            { 'value': 125, 'name': '7+', 'type': GradeSystem.UIAA },
            { 'value': 130, 'name': '7+/8-', 'type': GradeSystem.UIAA },
            { 'value': 135, 'name': '8-', 'type': GradeSystem.UIAA },
            { 'value': 140, 'name': '8', 'type': GradeSystem.UIAA },
            { 'value': 145, 'name': '8+', 'type': GradeSystem.UIAA },
            { 'value': 150, 'name': '8+/9-', 'type': GradeSystem.UIAA },
            { 'value': 155, 'name': '9-', 'type': GradeSystem.UIAA },
            { 'value': 160, 'name': '9', 'type': GradeSystem.UIAA },
            { 'value': 165, 'name': '9+', 'type': GradeSystem.UIAA },
            { 'value': 170, 'name': '9+/10-', 'type': GradeSystem.UIAA },
            { 'value': 175, 'name': '10-', 'type': GradeSystem.UIAA },
            { 'value': 180, 'name': '10', 'type': GradeSystem.UIAA },
            { 'value': 185, 'name': '10+', 'type': GradeSystem.UIAA },
            { 'value': 190, 'name': '11-', 'type': GradeSystem.UIAA },
            { 'value': 195, 'name': '11-/11', 'type': GradeSystem.UIAA },
            { 'value': 200, 'name': '11', 'type': GradeSystem.UIAA },
            { 'value': 205, 'name': '11+', 'type': GradeSystem.UIAA },
            { 'value': 210, 'name': '12-', 'type': GradeSystem.UIAA },
            { 'value': 215, 'name': '12', 'type': GradeSystem.UIAA },
            { 'value': 220, 'name': '12+', 'type': GradeSystem.UIAA },
            { 'value': 225, 'name': '12+/13-', 'type': GradeSystem.UIAA },
        ],
        GradeSystem.B: [
            { 'value': 20, 'name': 'B0', 'type': GradeSystem.B },
            { 'value': 35, 'name': 'B1', 'type': GradeSystem.B },
            { 'value': 45, 'name': 'B2', 'type': GradeSystem.B },
            { 'value': 52, 'name': 'B3', 'type': GradeSystem.B },
            { 'value': 55, 'name': 'B4', 'type': GradeSystem.B },
            { 'value': 65, 'name': 'B5', 'type': GradeSystem.B },
            { 'value': 80, 'name': 'B6', 'type': GradeSystem.B },
            { 'value': 85, 'name': 'B7', 'type': GradeSystem.B },
            { 'value': 90, 'name': 'B8', 'type': GradeSystem.B },
            { 'value': 100, 'name': 'B9', 'type': GradeSystem.B },
            { 'value': 105, 'name': 'B10', 'type': GradeSystem.B },
            { 'value': 110, 'name': 'B11', 'type': GradeSystem.B },
            { 'value': 115, 'name': 'B12', 'type': GradeSystem.B },
            { 'value': 120, 'name': 'B13', 'type': GradeSystem.B },
            { 'value': 130, 'name': 'B14', 'type': GradeSystem.B },
            { 'value': 135, 'name': 'B15', 'type': GradeSystem.B },
            { 'value': 140, 'name': 'B16', 'type': GradeSystem.B },
            { 'value': 145, 'name': 'B17', 'type': GradeSystem.B },
        ],
        GradeSystem.V: [
            { 'value': 20, 'name': 'VB', 'type': GradeSystem.V },
            { 'value': 25, 'name': 'V0-', 'type': GradeSystem.V },
            { 'value': 35, 'name': 'V0', 'type': GradeSystem.V },
            { 'value': 45, 'name': 'V0+', 'type': GradeSystem.V },
            { 'value': 52, 'name': 'V1', 'type': GradeSystem.V },
            { 'value': 55, 'name': 'V2', 'type': GradeSystem.V },
            { 'value': 60, 'name': 'V3', 'type': GradeSystem.V },
            { 'value': 65, 'name': 'V3+', 'type': GradeSystem.V },
            { 'value': 70, 'name': 'V4', 'type': GradeSystem.V },
            { 'value': 75, 'name': 'V4+', 'type': GradeSystem.V },
            { 'value': 80, 'name': 'V5', 'type': GradeSystem.V },
            { 'value': 85, 'name': 'V6', 'type': GradeSystem.V },
            { 'value': 90, 'name': 'V7', 'type': GradeSystem.V },
            { 'value': 100, 'name': 'V8', 'type': GradeSystem.V },
            { 'value': 105, 'name': 'V9', 'type': GradeSystem.V },
            { 'value': 110, 'name': 'V10', 'type': GradeSystem.V },
            { 'value': 115, 'name': 'V11', 'type': GradeSystem.V },
            { 'value': 120, 'name': 'V12', 'type': GradeSystem.V },
            { 'value': 125, 'name': 'V13', 'type': GradeSystem.V },
            { 'value': 130, 'name': 'V14', 'type': GradeSystem.V },
            { 'value': 135, 'name': 'V15', 'type': GradeSystem.V },
            { 'value': 140, 'name': 'V16', 'type': GradeSystem.V },
            { 'value': 145, 'name': 'V17', 'type': GradeSystem.V },
        ],
        GradeSystem.YOSEMITE: [
            { 'value': 20, 'name': '5.2', 'type': GradeSystem.YOSEMITE },
            { 'value': 30, 'name': '5.3', 'type': GradeSystem.YOSEMITE },
            { 'value': 40, 'name': '5.4', 'type': GradeSystem.YOSEMITE },
            { 'value': 50, 'name': '5.5', 'type': GradeSystem.YOSEMITE },
            { 'value': 60, 'name': '5.6', 'type': GradeSystem.YOSEMITE },
            { 'value': 80, 'name': '5.7', 'type': GradeSystem.YOSEMITE },
            { 'value': 90, 'name': '5.8', 'type': GradeSystem.YOSEMITE },
            { 'value': 100, 'name': '5.9', 'type': GradeSystem.YOSEMITE },
            { 'value': 110, 'name': '5.10a', 'type': GradeSystem.YOSEMITE },
            { 'value': 115, 'name': '5.10b', 'type': GradeSystem.YOSEMITE },
            { 'value': 117, 'name': '5.10c', 'type': GradeSystem.YOSEMITE },
            { 'value': 120, 'name': '5.10d', 'type': GradeSystem.YOSEMITE },
            { 'value': 125, 'name': '5.11a', 'type': GradeSystem.YOSEMITE },
            { 'value': 130, 'name': '5.11b', 'type': GradeSystem.YOSEMITE },
            { 'value': 135, 'name': '5.11c', 'type': GradeSystem.YOSEMITE },
            { 'value': 140, 'name': '5.11d', 'type': GradeSystem.YOSEMITE },
            { 'value': 145, 'name': '5.12a', 'type': GradeSystem.YOSEMITE },
            { 'value': 150, 'name': '5.12b', 'type': GradeSystem.YOSEMITE },
            { 'value': 155, 'name': '5.12c', 'type': GradeSystem.YOSEMITE },
            { 'value': 160, 'name': '5.12d', 'type': GradeSystem.YOSEMITE },
            { 'value': 165, 'name': '5.13a', 'type': GradeSystem.YOSEMITE },
            { 'value': 170, 'name': '5.13b', 'type': GradeSystem.YOSEMITE },
            { 'value': 175, 'name': '5.13c', 'type': GradeSystem.YOSEMITE },
            { 'value': 180, 'name': '5.13d', 'type': GradeSystem.YOSEMITE },
            { 'value': 185, 'name': '5.14a', 'type': GradeSystem.YOSEMITE },
            { 'value': 190, 'name': '5.14b', 'type': GradeSystem.YOSEMITE },
            { 'value': 195, 'name': '5.14c', 'type': GradeSystem.YOSEMITE },
            { 'value': 200, 'name': '5.14d', 'type': GradeSystem.YOSEMITE },
            { 'value': 205, 'name': '5.15a', 'type': GradeSystem.YOSEMITE },
            { 'value': 210, 'name': '5.15b', 'type': GradeSystem.YOSEMITE },
            { 'value': 215, 'name': '5.15c', 'type': GradeSystem.YOSEMITE },
            { 'value': 220, 'name': '5.15d', 'type': GradeSystem.YOSEMITE },
            { 'value': 225, 'name': '5.16a', 'type': GradeSystem.YOSEMITE },
        ]
    }