using Climbing.Guide.Api.Application.Interfaces;
using Climbing.Guide.Api.Domain.Entities;
using System.Collections.Generic;

namespace Climbing.Guide.Api.Application.Services {
   internal class StaticContext : IStaticContext {
      private static readonly IDictionary<GradeSystemType, IEnumerable<Grade>> _grades =
         new Dictionary<GradeSystemType, IEnumerable<Grade>>() {
            { GradeSystemType.French, new [] {
               new Grade() { Value = 20, Name = "3a", GradeType = GradeSystemType.French },
               new Grade() { Value = 25, Name = "3a+", GradeType = GradeSystemType.French },
               new Grade() { Value = 30, Name = "3b", GradeType = GradeSystemType.French },
               new Grade() { Value = 35, Name = "3b+", GradeType = GradeSystemType.French },
               new Grade() { Value = 40, Name = "3c", GradeType = GradeSystemType.French },
               new Grade() { Value = 45, Name = "3c+", GradeType = GradeSystemType.French },
               new Grade() { Value = 50, Name = "4a", GradeType = GradeSystemType.French },
               new Grade() { Value = 55, Name = "4a+", GradeType = GradeSystemType.French },
               new Grade() { Value = 60, Name = "4b", GradeType = GradeSystemType.French },
               new Grade() { Value = 65, Name = "4b+", GradeType = GradeSystemType.French },
               new Grade() { Value = 70, Name = "4c", GradeType = GradeSystemType.French },
               new Grade() { Value = 75, Name = "4c+", GradeType = GradeSystemType.French },
               new Grade() { Value = 80, Name = "5a", GradeType = GradeSystemType.French },
               new Grade() { Value = 85, Name = "5a+", GradeType = GradeSystemType.French },
               new Grade() { Value = 90, Name = "5b", GradeType = GradeSystemType.French },
               new Grade() { Value = 95, Name = "5b+", GradeType = GradeSystemType.French },
               new Grade() { Value = 100, Name = "5c", GradeType = GradeSystemType.French },
               new Grade() { Value = 105, Name = "5c+", GradeType = GradeSystemType.French },
               new Grade() { Value = 110, Name = "6a", GradeType = GradeSystemType.French },
               new Grade() { Value = 115, Name = "6a+", GradeType = GradeSystemType.French },
               new Grade() { Value = 120, Name = "6b", GradeType = GradeSystemType.French },
               new Grade() { Value = 125, Name = "6b+", GradeType = GradeSystemType.French },
               new Grade() { Value = 130, Name = "6c", GradeType = GradeSystemType.French },
               new Grade() { Value = 135, Name = "6c+", GradeType = GradeSystemType.French },
               new Grade() { Value = 140, Name = "7a", GradeType = GradeSystemType.French },
               new Grade() { Value = 145, Name = "7a+", GradeType = GradeSystemType.French },
               new Grade() { Value = 150, Name = "7b", GradeType = GradeSystemType.French },
               new Grade() { Value = 155, Name = "7b+", GradeType = GradeSystemType.French },
               new Grade() { Value = 160, Name = "7c", GradeType = GradeSystemType.French },
               new Grade() { Value = 165, Name = "7c+", GradeType = GradeSystemType.French },
               new Grade() { Value = 170, Name = "8a", GradeType = GradeSystemType.French },
               new Grade() { Value = 175, Name = "8a+", GradeType = GradeSystemType.French },
               new Grade() { Value = 180, Name = "8b", GradeType = GradeSystemType.French },
               new Grade() { Value = 185, Name = "8b+", GradeType = GradeSystemType.French },
               new Grade() { Value = 190, Name = "8c", GradeType = GradeSystemType.French },
               new Grade() { Value = 192, Name = "8c/+", GradeType = GradeSystemType.French },
               new Grade() { Value = 195, Name = "8c+", GradeType = GradeSystemType.French },
               new Grade() { Value = 197, Name = "8c+/9a", GradeType = GradeSystemType.French },
               new Grade() { Value = 200, Name = "9a", GradeType = GradeSystemType.French },
               new Grade() { Value = 205, Name = "9a+", GradeType = GradeSystemType.French },
               new Grade() { Value = 210, Name = "9b", GradeType = GradeSystemType.French },
               new Grade() { Value = 215, Name = "9b+", GradeType = GradeSystemType.French },
               new Grade() { Value = 220, Name = "9c", GradeType = GradeSystemType.French },
               new Grade() { Value = 225, Name = "9c+", GradeType = GradeSystemType.French },
            } },
            { GradeSystemType.Uiaa, new [] {
               new Grade() { Value = 20, Name = "3-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 30, Name = "3", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 40, Name = "3+", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 50, Name = "4-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 60, Name = "4", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 70, Name = "4+", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 80, Name = "5-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 85, Name = "5", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 90, Name = "5+", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 95, Name = "5+/6-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 100, Name = "6-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 105, Name = "6", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 110, Name = "6+", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 115, Name = "6+/7-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 117, Name = "7-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 120, Name = "7", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 125, Name = "7+", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 130, Name = "7+/8-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 135, Name = "8-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 140, Name = "8", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 145, Name = "8+", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 150, Name = "8+/9-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 155, Name = "9-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 160, Name = "9", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 165, Name = "9+", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 170, Name = "9+/10-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 175, Name = "10-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 180, Name = "10", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 185, Name = "10+", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 190, Name = "11-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 195, Name = "11-/11", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 200, Name = "11", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 205, Name = "11+", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 210, Name = "12-", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 215, Name = "12", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 220, Name = "12+", GradeType = GradeSystemType.Uiaa },
               new Grade() { Value = 225, Name = "12+/13-", GradeType = GradeSystemType.Uiaa },
            } },
            { GradeSystemType.Yosemite, new [] {
               new Grade() { Value = 20, Name = "5.2", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 30, Name = "5.3", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 40, Name = "5.4", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 50, Name = "5.5", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 60, Name = "5.6", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 80, Name = "5.7", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 90, Name = "5.8", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 100, Name = "5.9", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 110, Name = "5.10a", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 115, Name = "5.10b", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 117, Name = "5.10c", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 120, Name = "5.10d", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 125, Name = "5.11a", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 130, Name = "5.11b", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 135, Name = "5.11c", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 140, Name = "5.11d", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 145, Name = "5.12a", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 150, Name = "5.12b", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 155, Name = "5.12c", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 160, Name = "5.12d", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 165, Name = "5.13a", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 170, Name = "5.13b", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 175, Name = "5.13c", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 180, Name = "5.13d", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 185, Name = "5.14a", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 190, Name = "5.14b", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 195, Name = "5.14c", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 200, Name = "5.14d", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 205, Name = "5.15a", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 210, Name = "5.15b", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 215, Name = "5.15c", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 220, Name = "5.15d", GradeType = GradeSystemType.Yosemite },
               new Grade() { Value = 225, Name = "5.16a", GradeType = GradeSystemType.Yosemite },
            } },
            { GradeSystemType.Font, new [] {
               new Grade() { Value = 20, Name = "3", GradeType = GradeSystemType.Font },
               new Grade() { Value = 25, Name = "4-", GradeType = GradeSystemType.Font },
               new Grade() { Value = 30, Name = "4", GradeType = GradeSystemType.Font },
               new Grade() { Value = 35, Name = "4+", GradeType = GradeSystemType.Font },
               new Grade() { Value = 40, Name = "5-", GradeType = GradeSystemType.Font },
               new Grade() { Value = 45, Name = "5", GradeType = GradeSystemType.Font },
               new Grade() { Value = 50, Name = "5+", GradeType = GradeSystemType.Font },
               new Grade() { Value = 55, Name = "6A", GradeType = GradeSystemType.Font },
               new Grade() { Value = 60, Name = "6A+", GradeType = GradeSystemType.Font },
               new Grade() { Value = 65, Name = "6B", GradeType = GradeSystemType.Font },
               new Grade() { Value = 70, Name = "6B+", GradeType = GradeSystemType.Font },
               new Grade() { Value = 75, Name = "6C", GradeType = GradeSystemType.Font },
               new Grade() { Value = 80, Name = "6C+", GradeType = GradeSystemType.Font },
               new Grade() { Value = 85, Name = "7A", GradeType = GradeSystemType.Font },
               new Grade() { Value = 90, Name = "7A+", GradeType = GradeSystemType.Font },
               new Grade() { Value = 95, Name = "7B", GradeType = GradeSystemType.Font },
               new Grade() { Value = 100, Name = "7B+", GradeType = GradeSystemType.Font },
               new Grade() { Value = 105, Name = "7C", GradeType = GradeSystemType.Font },
               new Grade() { Value = 110, Name = "7C+", GradeType = GradeSystemType.Font },
               new Grade() { Value = 115, Name = "8A", GradeType = GradeSystemType.Font },
               new Grade() { Value = 120, Name = "8A+", GradeType = GradeSystemType.Font },
               new Grade() { Value = 125, Name = "8B", GradeType = GradeSystemType.Font },
               new Grade() { Value = 130, Name = "8B+", GradeType = GradeSystemType.Font },
               new Grade() { Value = 135, Name = "8C", GradeType = GradeSystemType.Font },
               new Grade() { Value = 140, Name = "8C+", GradeType = GradeSystemType.Font },
               new Grade() { Value = 145, Name = "9A", GradeType = GradeSystemType.Font },
            } },
            { GradeSystemType.V, new [] {
               new Grade() { Value = 20, Name = "VB", GradeType = GradeSystemType.V },
               new Grade() { Value = 25, Name = "V0-", GradeType = GradeSystemType.V },
               new Grade() { Value = 35, Name = "V0", GradeType = GradeSystemType.V },
               new Grade() { Value = 45, Name = "V0+", GradeType = GradeSystemType.V },
               new Grade() { Value = 52, Name = "V1", GradeType = GradeSystemType.V },
               new Grade() { Value = 55, Name = "V2", GradeType = GradeSystemType.V },
               new Grade() { Value = 60, Name = "V3", GradeType = GradeSystemType.V },
               new Grade() { Value = 65, Name = "V3+", GradeType = GradeSystemType.V },
               new Grade() { Value = 70, Name = "V4", GradeType = GradeSystemType.V },
               new Grade() { Value = 75, Name = "V4+", GradeType = GradeSystemType.V },
               new Grade() { Value = 80, Name = "V5", GradeType = GradeSystemType.V },
               new Grade() { Value = 85, Name = "V6", GradeType = GradeSystemType.V },
               new Grade() { Value = 90, Name = "V7", GradeType = GradeSystemType.V },
               new Grade() { Value = 100, Name = "V8", GradeType = GradeSystemType.V },
               new Grade() { Value = 105, Name = "V9", GradeType = GradeSystemType.V },
               new Grade() { Value = 110, Name = "V10", GradeType = GradeSystemType.V },
               new Grade() { Value = 115, Name = "V11", GradeType = GradeSystemType.V },
               new Grade() { Value = 120, Name = "V12", GradeType = GradeSystemType.V },
               new Grade() { Value = 125, Name = "V13", GradeType = GradeSystemType.V },
               new Grade() { Value = 130, Name = "V14", GradeType = GradeSystemType.V },
               new Grade() { Value = 135, Name = "V15", GradeType = GradeSystemType.V },
               new Grade() { Value = 140, Name = "V16", GradeType = GradeSystemType.V },
               new Grade() { Value = 145, Name = "V17", GradeType = GradeSystemType.V },
            } },
            { GradeSystemType.B, new [] {
               new Grade() { Value = 20, Name = "B0", GradeType = GradeSystemType.B },
               new Grade() { Value = 35, Name = "B1", GradeType = GradeSystemType.B },
               new Grade() { Value = 45, Name = "B2", GradeType = GradeSystemType.B },
               new Grade() { Value = 52, Name = "B3", GradeType = GradeSystemType.B },
               new Grade() { Value = 55, Name = "B4", GradeType = GradeSystemType.B },
               new Grade() { Value = 65, Name = "B5", GradeType = GradeSystemType.B },
               new Grade() { Value = 80, Name = "B6", GradeType = GradeSystemType.B },
               new Grade() { Value = 85, Name = "B7", GradeType = GradeSystemType.B },
               new Grade() { Value = 90, Name = "B8", GradeType = GradeSystemType.B },
               new Grade() { Value = 100, Name = "B9", GradeType = GradeSystemType.B },
               new Grade() { Value = 105, Name = "B10", GradeType = GradeSystemType.B },
               new Grade() { Value = 110, Name = "B11", GradeType = GradeSystemType.B },
               new Grade() { Value = 115, Name = "B12", GradeType = GradeSystemType.B },
               new Grade() { Value = 120, Name = "B13", GradeType = GradeSystemType.B },
               new Grade() { Value = 130, Name = "B14", GradeType = GradeSystemType.B },
               new Grade() { Value = 135, Name = "B15", GradeType = GradeSystemType.B },
               new Grade() { Value = 140, Name = "B16", GradeType = GradeSystemType.B },
               new Grade() { Value = 145, Name = "B17", GradeType = GradeSystemType.B },
            } }
         };
      public IEnumerable<GradeSystem> GradeSystems { get; } = new GradeSystem[] {
         new GradeSystem() {
            GradeType = GradeSystemType.French,
            RouteType = RouteType.Sport,
            Name = "French"
         },
         new GradeSystem() {
            GradeType = GradeSystemType.Uiaa,
            RouteType = RouteType.Sport,
            Name = "UIAA"
         },
         new GradeSystem() {
            GradeType = GradeSystemType.Yosemite,
            RouteType = RouteType.Sport,
            Name = "Yosemite"
         },
         new GradeSystem() {
            GradeType = GradeSystemType.Font,
            RouteType = RouteType.Boulder,
            Name = "Font Bouldering"
         },
         new GradeSystem() {
            GradeType = GradeSystemType.V,
            RouteType = RouteType.Boulder,
            Name = "V Grade"
         },
         new GradeSystem() {
            GradeType = GradeSystemType.B,
            RouteType = RouteType.Boulder,
            Name = "Peak Bouldering"
         },
         new GradeSystem() {
            GradeType = GradeSystemType.French,
            RouteType = RouteType.Trad,
            Name = "French"
         },
         new GradeSystem() {
            GradeType = GradeSystemType.Uiaa,
            RouteType = RouteType.Trad,
            Name = "UIAA"
         },
         new GradeSystem() {
            GradeType = GradeSystemType.Yosemite,
            RouteType = RouteType.Trad,
            Name = "Yosemite"
         },
      };

      public IEnumerable<Grade> GetGrades(GradeSystemType gradeSystemType) {
         return _grades[gradeSystemType];
      }
   }
}
