// <auto-generated />
using System;
using Climbing.Guide.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Climbing.Guide.Api.Infrastructure.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20191126110858_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Accomodations")
                        .HasColumnType("ntext");

                    b.Property<string>("Approach")
                        .HasColumnType("ntext");

                    b.Property<string>("ApprovedById")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("AreasContainerId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descent")
                        .HasColumnType("ntext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ethics")
                        .HasColumnType("ntext");

                    b.Property<string>("History")
                        .HasColumnType("ntext");

                    b.Property<string>("Info")
                        .HasColumnType("ntext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Restrictions")
                        .HasColumnType("ntext");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("AreasContainerId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ParentId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Area");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Area");
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Code2")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Code3")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = "9235cd70-220e-47d9-b76e-17a81d1db7f5",
                            Code2 = "AF",
                            Code3 = "AFG",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = "44b36fff-1d8a-42e8-aa06-5300db6f73a3",
                            Code2 = "AF",
                            Code3 = "AFG",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = "21fcca7d-044e-43f1-a71f-f44a39b6db6d",
                            Code2 = "AX",
                            Code3 = "ALA",
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = "597ad1ff-4805-42f7-bfdf-d3fc1b6a2ddc",
                            Code2 = "AL",
                            Code3 = "ALB",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = "5ba0f206-408c-49a6-af79-b5bb4ba310ef",
                            Code2 = "DZ",
                            Code3 = "DZA",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = "5603b08a-579d-42fa-850c-f9e21435e2ec",
                            Code2 = "AS",
                            Code3 = "ASM",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = "6351dd0a-aeee-4368-868c-8ae9c183a347",
                            Code2 = "AD",
                            Code3 = "AND",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = "53cb6e19-29a2-423c-a4a4-cb27f3a1ddd2",
                            Code2 = "AO",
                            Code3 = "AGO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = "9d3a5b4e-9cf2-45f9-9b00-7b3ee7648da3",
                            Code2 = "AI",
                            Code3 = "AIA",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = "bc75ad02-314f-40cf-ba35-9df2e17d9a60",
                            Code2 = "AQ",
                            Code3 = "ATA",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = "69b4f6df-6ac9-49bb-9814-161f280d2397",
                            Code2 = "AG",
                            Code3 = "ATG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = "70ead369-9f79-4f46-b621-9283621abd2b",
                            Code2 = "AR",
                            Code3 = "ARG",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = "52add52d-ba30-41fa-bd7f-86c4a5147448",
                            Code2 = "AM",
                            Code3 = "ARM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = "5b2fa68a-af76-44f2-bf1c-1adbd8df3d30",
                            Code2 = "AW",
                            Code3 = "ABW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = "e7845cde-5cd4-443d-bbc6-04248f406314",
                            Code2 = "AU",
                            Code3 = "AUS",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = "73100317-77ca-4289-a346-d55d6726a772",
                            Code2 = "AT",
                            Code3 = "AUT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = "3de04735-d5b2-48ba-9440-e14b8682ce65",
                            Code2 = "AZ",
                            Code3 = "AZE",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = "9f067454-e5eb-4721-96d0-9ab833414b5c",
                            Code2 = "BS",
                            Code3 = "BHS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = "cd062feb-6656-4cf2-a3bc-1214db15f8ca",
                            Code2 = "BH",
                            Code3 = "BHR",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = "d7bfe1d8-2b4a-4d29-9ae7-a7faa9ab955c",
                            Code2 = "BD",
                            Code3 = "BGD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = "5ffad66c-c7dc-405e-84f0-be9ea29204b9",
                            Code2 = "BB",
                            Code3 = "BRB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = "7d33ab08-1cf9-44b4-bb70-af4f193c6fa5",
                            Code2 = "BY",
                            Code3 = "BLR",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = "11bb4d8b-83ff-41f7-9279-a5c6d812c650",
                            Code2 = "BE",
                            Code3 = "BEL",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = "8d7e00ec-df66-4086-8113-f4b871a172c7",
                            Code2 = "BZ",
                            Code3 = "BLZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = "55de473c-33f9-4e66-ba3a-39d29269b2db",
                            Code2 = "BJ",
                            Code3 = "BEN",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = "71d33801-de67-4dcb-b837-00a4021fb080",
                            Code2 = "BM",
                            Code3 = "BMU",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = "98219aae-943d-4ed8-8150-336f8b520866",
                            Code2 = "BT",
                            Code3 = "BTN",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = "584acf24-730c-4671-98da-8bdfa8eb1759",
                            Code2 = "BO",
                            Code3 = "BOL",
                            Name = "Bolivia (Plurinational State of)"
                        },
                        new
                        {
                            Id = "caf7951b-4399-4188-8948-0cd6331c57fa",
                            Code2 = "BQ",
                            Code3 = "BES",
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = "5cf2d0fc-7682-4566-b7f8-cd6203af6b38",
                            Code2 = "BA",
                            Code3 = "BIH",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = "4d6baf58-5226-4750-9e62-c834efc8a704",
                            Code2 = "BA",
                            Code3 = "BIH",
                            Name = "Bosnia & Herzegowina"
                        },
                        new
                        {
                            Id = "c1d6ea0c-340b-47ec-b88a-12818d969ac3",
                            Code2 = "BW",
                            Code3 = "BWA",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = "c1cb7af8-e166-4275-bb90-92cfbdacd716",
                            Code2 = "BV",
                            Code3 = "BVT",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = "43c02c42-2421-4f86-8295-f7f57f5b9a6d",
                            Code2 = "BR",
                            Code3 = "BRA",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = "31ea47ad-8119-464f-976e-03dccc01f7f5",
                            Code2 = "IO",
                            Code3 = "IOT",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = "b7722feb-7b7f-4551-9a22-c204ae4507f8",
                            Code2 = "BN",
                            Code3 = "BRN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = "e4bcefdc-b81d-42fa-a948-f0461ce200e3",
                            Code2 = "BG",
                            Code3 = "BGR",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = "ae2ba562-091a-49bf-b7fc-9163ba1cb456",
                            Code2 = "BF",
                            Code3 = "BFA",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = "588d61d1-762a-4d5b-9e4f-3808d821cfff",
                            Code2 = "BI",
                            Code3 = "BDI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = "0d72ef57-3280-4964-9110-bcdd453c21c4",
                            Code2 = "CV",
                            Code3 = "CPV",
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = "48badab7-dea1-494a-b18e-e79a3dbc7f29",
                            Code2 = "KH",
                            Code3 = "KHM",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = "aa4ddd39-b13f-4ad5-ae1b-dc3400a7eb5f",
                            Code2 = "CM",
                            Code3 = "CMR",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = "876815c3-5a3b-4218-98a5-0578eb4f69c9",
                            Code2 = "CA",
                            Code3 = "CAN",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = "c28fb193-4250-4adc-a2da-0e6c12836482",
                            Code2 = "KY",
                            Code3 = "CYM",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = "1852a666-c2e0-49c4-87a7-f32054e929ee",
                            Code2 = "CF",
                            Code3 = "CAF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = "ef8a34f8-cbd0-4a53-acc1-69b41fd25b81",
                            Code2 = "TD",
                            Code3 = "TCD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = "fff7597d-cba5-4c7d-9e8f-461b81a44e05",
                            Code2 = "CL",
                            Code3 = "CHL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = "b958c3e6-f270-43f3-a3e3-9b540fbeb14c",
                            Code2 = "CN",
                            Code3 = "CHN",
                            Name = "China"
                        },
                        new
                        {
                            Id = "3a66afa0-cefa-4902-bdd5-1ce64488f754",
                            Code2 = "CX",
                            Code3 = "CXR",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = "b52fb38f-f387-45ff-be26-2d874b798ed1",
                            Code2 = "CC",
                            Code3 = "CCK",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = "90bedfdf-7760-42e3-b74a-36bae7311810",
                            Code2 = "CO",
                            Code3 = "COL",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = "591db77c-303d-4b91-bf20-4fdb71eaeb5b",
                            Code2 = "KM",
                            Code3 = "COM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = "a7e7c7cb-6476-42de-8f64-902c6b9b3ade",
                            Code2 = "CG",
                            Code3 = "COG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = "3a258673-4522-4ce3-a015-a7488c4f9914",
                            Code2 = "CD",
                            Code3 = "COD",
                            Name = "Congo (Democratic Republic of the)"
                        },
                        new
                        {
                            Id = "5996e482-56c9-40cd-a2b9-a16ff2b054c5",
                            Code2 = "CK",
                            Code3 = "COK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = "8826c780-657c-4f3d-a884-cc1738ea71f1",
                            Code2 = "CR",
                            Code3 = "CRI",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = "c013b669-802d-453b-80b9-0b158fbb8a21",
                            Code2 = "CI",
                            Code3 = "CIV",
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = "feefbafb-9029-4244-a388-4dd51f69f517",
                            Code2 = "HR",
                            Code3 = "HRV",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = "d5f8be31-b73e-4db1-a2e1-e645a14612c5",
                            Code2 = "CU",
                            Code3 = "CUB",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = "6cc28639-c3ed-4e95-8149-06b4cf4ed61b",
                            Code2 = "CW",
                            Code3 = "CUW",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = "57fc8305-67c9-4b75-aca3-1cb40bb6a5e1",
                            Code2 = "CY",
                            Code3 = "CYP",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = "de939231-ee20-4a01-87b2-a9bc0169497c",
                            Code2 = "CZ",
                            Code3 = "CZE",
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = "9ec999b6-9104-41c4-a3ed-707b54f3e60f",
                            Code2 = "CZ",
                            Code3 = "CZE",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = "f13dba85-167c-4757-9794-096c5014d032",
                            Code2 = "DK",
                            Code3 = "DNK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = "8364a2c7-c33d-42ba-a431-e510c5458ed3",
                            Code2 = "DJ",
                            Code3 = "DJI",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = "70c0dbf1-12a9-499e-aef5-ef3c92ad8e37",
                            Code2 = "DM",
                            Code3 = "DMA",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = "faaf6f33-d8cd-4c4f-b0a5-19860a6f1290",
                            Code2 = "DO",
                            Code3 = "DOM",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = "9b0bc9c1-bc01-4ee5-b46c-c1689076ec24",
                            Code2 = "EC",
                            Code3 = "ECU",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = "7ad18a2a-30a5-4407-9308-7e88adb706d9",
                            Code2 = "EG",
                            Code3 = "EGY",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = "c80f3585-19e3-427c-abf4-042acdd257a3",
                            Code2 = "SV",
                            Code3 = "SLV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = "52889d45-fd3e-4154-a44f-cc483bf822ab",
                            Code2 = "GQ",
                            Code3 = "GNQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = "3d4bde3f-9d6f-4882-9398-4e5df284dd19",
                            Code2 = "ER",
                            Code3 = "ERI",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = "e9043d37-7aca-4d97-abd4-439afe4ff536",
                            Code2 = "EE",
                            Code3 = "EST",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = "75cf2f58-8b9a-4553-8f68-3a7f2df45ee8",
                            Code2 = "SZ",
                            Code3 = "SWZ",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = "72add91d-b063-4706-a1f5-d999ff751504",
                            Code2 = "ET",
                            Code3 = "ETH",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = "9f550658-c521-474d-9aae-65c12effc11f",
                            Code2 = "FK",
                            Code3 = "FLK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = "e9a63c1a-6d15-435e-8705-3cfaeb443571",
                            Code2 = "FO",
                            Code3 = "FRO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = "c54d79f7-b117-45a1-a09e-066542bf9e3d",
                            Code2 = "FJ",
                            Code3 = "FJI",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = "8057be7d-9e49-4721-9872-b3274dab1a50",
                            Code2 = "FI",
                            Code3 = "FIN",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = "c87f2f17-8557-48ee-ac18-f94e0ea13c81",
                            Code2 = "FR",
                            Code3 = "FRA",
                            Name = "France"
                        },
                        new
                        {
                            Id = "835f5ef4-c339-471d-bac1-694af0323a9b",
                            Code2 = "GF",
                            Code3 = "GUF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = "c07e0f0c-158f-4ba6-b953-f9b7faa31516",
                            Code2 = "PF",
                            Code3 = "PYF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = "e14e9227-0f97-473f-8008-095572d8de4c",
                            Code2 = "TF",
                            Code3 = "ATF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = "6650ed21-db40-4554-a965-28f2e34ed808",
                            Code2 = "GA",
                            Code3 = "GAB",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = "b7c25e29-2a59-4882-8a36-9aed9fe4de1c",
                            Code2 = "GM",
                            Code3 = "GMB",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = "a1460ffe-64ad-408e-9b37-990f0d36c697",
                            Code2 = "GE",
                            Code3 = "GEO",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = "b8ca640b-0a6b-4c29-bd4a-9a8c76d4ccb2",
                            Code2 = "DE",
                            Code3 = "DEU",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = "4d22d98a-fcc1-4b4a-aa57-749ea8decf0d",
                            Code2 = "GH",
                            Code3 = "GHA",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = "25df0670-d028-426c-994e-a5db33614fac",
                            Code2 = "GI",
                            Code3 = "GIB",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = "9f79f61b-3821-42a5-88fc-687a52fca613",
                            Code2 = "GR",
                            Code3 = "GRC",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = "4bddbebc-5097-4d2a-9cd7-c2d654d6e7f2",
                            Code2 = "GL",
                            Code3 = "GRL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = "4520c6a8-c0fd-45f5-90a6-4fc78c6f0951",
                            Code2 = "GD",
                            Code3 = "GRD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = "c731f2b6-d69e-4c4a-839d-dc4db2a80369",
                            Code2 = "GP",
                            Code3 = "GLP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = "3230ff87-4f7d-41e1-8be1-bb2d33d3b9a5",
                            Code2 = "GU",
                            Code3 = "GUM",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = "ffbcc443-d529-4427-ae47-024c6fd6ece8",
                            Code2 = "GT",
                            Code3 = "GTM",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = "d4f95491-d7c2-4919-8d19-f87e22dca34f",
                            Code2 = "GG",
                            Code3 = "GGY",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = "9aa0c3eb-97ab-46c2-8909-9b6d7a3b34e5",
                            Code2 = "GN",
                            Code3 = "GIN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = "1e8bd3f1-a52d-4d75-bb58-a2146255a792",
                            Code2 = "GW",
                            Code3 = "GNB",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = "0c82439e-e73f-43c9-8651-01f4f30a2521",
                            Code2 = "GY",
                            Code3 = "GUY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = "5de8d9d5-1be5-4d14-b391-8dfedfb4f23f",
                            Code2 = "HT",
                            Code3 = "HTI",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = "4e4c0446-5fc0-4811-8536-9b3f23344616",
                            Code2 = "HM",
                            Code3 = "HMD",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = "6aa16a10-71ad-4bf6-a4d0-80095a9d92b2",
                            Code2 = "VA",
                            Code3 = "VAT",
                            Name = "Holy See"
                        },
                        new
                        {
                            Id = "e767804c-cb3f-4502-bc0f-b732208014ff",
                            Code2 = "HN",
                            Code3 = "HND",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = "b8818db5-8922-4f7a-82d9-0141ad4a45a5",
                            Code2 = "HK",
                            Code3 = "HKG",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = "4725a19c-3abe-4609-b65a-01a9c47f2d89",
                            Code2 = "HU",
                            Code3 = "HUN",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = "25efcfa1-b91a-4bcb-b153-406651565651",
                            Code2 = "IS",
                            Code3 = "ISL",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = "54031f93-dfeb-43fe-b2d5-27b16e105d7b",
                            Code2 = "IN",
                            Code3 = "IND",
                            Name = "India"
                        },
                        new
                        {
                            Id = "e7039d66-7d6c-4f42-b5f1-6a79287c098d",
                            Code2 = "ID",
                            Code3 = "IDN",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = "e696352f-5a53-4b81-9109-0fab91ea1956",
                            Code2 = "IR",
                            Code3 = "IRN",
                            Name = "Iran (Islamic Republic of)"
                        },
                        new
                        {
                            Id = "68c633b0-a50e-4b26-b787-addf353fa502",
                            Code2 = "IR",
                            Code3 = "IRN",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = "b320d017-bb3b-48c4-8871-fe2cf1d6f8ac",
                            Code2 = "IQ",
                            Code3 = "IRQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = "1c91fb93-cbc0-4194-9a52-5fa839853034",
                            Code2 = "IE",
                            Code3 = "IRL",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = "0d9ab580-6175-468c-8318-9101445cd543",
                            Code2 = "IM",
                            Code3 = "IMN",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = "d738d352-9e4e-4222-b252-0eb3634e0228",
                            Code2 = "IL",
                            Code3 = "ISR",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = "e9e9e670-a51b-4743-a0f3-bed2451b564c",
                            Code2 = "IT",
                            Code3 = "ITA",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = "05abe794-8f0c-43ae-8305-9ac04d3a0830",
                            Code2 = "JM",
                            Code3 = "JAM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = "b7de5e6b-a00e-453a-992e-5d95680a0179",
                            Code2 = "JP",
                            Code3 = "JPN",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = "8687d0b7-0890-4ab6-a57e-8361220707ee",
                            Code2 = "JE",
                            Code3 = "JEY",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = "5f1a49be-f5da-42d7-b728-5e9fd068ec1a",
                            Code2 = "JO",
                            Code3 = "JOR",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = "0411bfb0-4b68-461a-a4d7-7f3997242a3c",
                            Code2 = "KZ",
                            Code3 = "KAZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = "5dcee40a-98b3-46fe-9e94-4aeac8c9cb2f",
                            Code2 = "KE",
                            Code3 = "KEN",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = "27f97629-1fa5-4fcd-8c58-8719f25080cb",
                            Code2 = "KI",
                            Code3 = "KIR",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = "1095ec61-6139-47ed-8d89-a814df34417d",
                            Code2 = "KP",
                            Code3 = "PRK",
                            Name = "Korea (Democratic People's Republic of)"
                        },
                        new
                        {
                            Id = "2f59b79e-ebcc-4a19-9641-e020ebaee3cd",
                            Code2 = "KR",
                            Code3 = "KOR",
                            Name = "Korea (Republic of)"
                        },
                        new
                        {
                            Id = "8822f89f-9246-4289-a96a-d8a176f6cf74",
                            Code2 = "KR",
                            Code3 = "KOR",
                            Name = "Korea"
                        },
                        new
                        {
                            Id = "13fbff1b-6c8d-41ee-9a21-15a24a9ab733",
                            Code2 = "KW",
                            Code3 = "KWT",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = "623ffb3b-4182-4462-9665-9e798960c885",
                            Code2 = "KG",
                            Code3 = "KGZ",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = "d95a00c5-a2bd-4d1f-bce7-5f28a2261305",
                            Code2 = "LA",
                            Code3 = "LAO",
                            Name = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            Id = "ee9fbb8c-76ce-4a0b-93cd-83eeafe15178",
                            Code2 = "LA",
                            Code3 = "LAO",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = "c39d6350-8857-433a-8c11-6c474c09ad7f",
                            Code2 = "LV",
                            Code3 = "LVA",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = "ab502518-caa8-4416-92f6-c22002ba19a0",
                            Code2 = "LB",
                            Code3 = "LBN",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = "eebde06a-be06-4c55-bdaf-c1f3256456d4",
                            Code2 = "LS",
                            Code3 = "LSO",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = "eeff84da-34b4-4509-b842-fb49031d7c91",
                            Code2 = "LR",
                            Code3 = "LBR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = "ecd2807b-21b8-48ea-990a-0545740e50d7",
                            Code2 = "LY",
                            Code3 = "LBY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = "f162f8fa-ab82-43ef-9e98-f57d879d2ea2",
                            Code2 = "LI",
                            Code3 = "LIE",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = "c5a72efb-9905-4de0-9ab7-b599aced788d",
                            Code2 = "LT",
                            Code3 = "LTU",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = "1dedcb24-ffce-4294-93c5-514d66fba942",
                            Code2 = "LU",
                            Code3 = "LUX",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = "0015a40a-a493-41e2-aebe-cbccd867c68c",
                            Code2 = "MO",
                            Code3 = "MAC",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = "67ef12fb-6c70-4763-bfc6-34575cfd6012",
                            Code2 = "MK",
                            Code3 = "MKD",
                            Name = "Macedonia (the former Yugoslav Republic of)"
                        },
                        new
                        {
                            Id = "c694b105-20f7-49ae-b621-86d06de1a29c",
                            Code2 = "MK",
                            Code3 = "MKD",
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = "3ca9a491-009d-4432-9551-6a52e97c9b21",
                            Code2 = "MG",
                            Code3 = "MDG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = "6cb29817-ac30-43af-a691-7e6220b3d415",
                            Code2 = "MW",
                            Code3 = "MWI",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = "5ca6b9d9-1c11-4b6c-b2b3-00a067ca3bb1",
                            Code2 = "MY",
                            Code3 = "MYS",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = "bfafec54-ee78-4e3c-8fb0-d677c6420ed4",
                            Code2 = "MV",
                            Code3 = "MDV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = "ea98b43b-379b-4860-862e-b3876b23ee08",
                            Code2 = "ML",
                            Code3 = "MLI",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = "c54afedf-fe46-49cb-baca-53ec0892d4a5",
                            Code2 = "MT",
                            Code3 = "MLT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = "e3385e5e-b497-4121-8c58-5f974f47f598",
                            Code2 = "MH",
                            Code3 = "MHL",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = "f71999a7-0183-41b1-af60-28cae942e45e",
                            Code2 = "MQ",
                            Code3 = "MTQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = "32585d9f-0bfa-4b0d-b28a-6633fc9e2a57",
                            Code2 = "MR",
                            Code3 = "MRT",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = "8e750165-45d0-4608-9fe0-fffcd0b497ac",
                            Code2 = "MU",
                            Code3 = "MUS",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = "deedbc18-ece9-49e7-b9c8-45721cc6c044",
                            Code2 = "YT",
                            Code3 = "MYT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = "ab87ae59-f9c7-4fce-bf2d-21895e0337d4",
                            Code2 = "MX",
                            Code3 = "MEX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = "59d96296-7a8c-41e2-9288-e38280542bd9",
                            Code2 = "FM",
                            Code3 = "FSM",
                            Name = "Micronesia (Federated States of)"
                        },
                        new
                        {
                            Id = "463b405f-7d27-4e31-88d0-f66c7e5a08c1",
                            Code2 = "MD",
                            Code3 = "MDA",
                            Name = "Moldova (Republic of)"
                        },
                        new
                        {
                            Id = "6220e302-7f3e-4c65-921d-b570b0da87be",
                            Code2 = "MC",
                            Code3 = "MCO",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = "8f1fb492-938a-4e4b-80b1-00588acb1ba5",
                            Code2 = "MN",
                            Code3 = "MNG",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = "d1e98f47-be26-491f-a345-ba094b0d09c7",
                            Code2 = "ME",
                            Code3 = "MNE",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = "7694799d-5d0a-4131-a84b-72b74ed6992f",
                            Code2 = "MS",
                            Code3 = "MSR",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = "eedb87e3-450d-485b-b285-9b222bd2228c",
                            Code2 = "MA",
                            Code3 = "MAR",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = "66556adb-f36c-471b-917f-fce7cc573b24",
                            Code2 = "MZ",
                            Code3 = "MOZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = "e366c7a4-1622-42b8-91ec-eb08e05c9e5d",
                            Code2 = "MM",
                            Code3 = "MMR",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = "e4c7f11c-6e2c-426f-9a43-a7390788393f",
                            Code2 = "NA",
                            Code3 = "NAM",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = "ad87db55-a77a-4896-af59-15bf504c1af0",
                            Code2 = "NR",
                            Code3 = "NRU",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = "f00a13db-1aca-42d7-a10c-02a0a88cdf80",
                            Code2 = "NP",
                            Code3 = "NPL",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = "d7b4a62a-e4bf-4ea7-ab68-87c8fadfa0d6",
                            Code2 = "NL",
                            Code3 = "NLD",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = "c9333810-a097-4a75-b0c5-afd22f6863c4",
                            Code2 = "NC",
                            Code3 = "NCL",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = "553af18b-f5a7-4d8d-aa77-573297891ad8",
                            Code2 = "NZ",
                            Code3 = "NZL",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = "b515fcf8-601b-4464-89dd-1c1e5d7a1098",
                            Code2 = "NI",
                            Code3 = "NIC",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = "6a80d61b-344f-4cd0-84b1-d8df1d447fde",
                            Code2 = "NE",
                            Code3 = "NER",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = "9eb55e10-f386-4d0e-9d3f-6e763970dbec",
                            Code2 = "NG",
                            Code3 = "NGA",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = "52849ef9-6ad6-4f4c-bbca-98a841736311",
                            Code2 = "NU",
                            Code3 = "NIU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = "2e6970b6-d5dd-4589-ba8b-393dae6aadc6",
                            Code2 = "NF",
                            Code3 = "NFK",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = "56998bee-caeb-4f2b-ae60-51de18e7d744",
                            Code2 = "MP",
                            Code3 = "MNP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = "497497c7-c13d-40bf-bda6-8cfe8efc1068",
                            Code2 = "NO",
                            Code3 = "NOR",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = "1b8259c4-eef8-4ac2-bcea-6e0d46d5bc42",
                            Code2 = "OM",
                            Code3 = "OMN",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = "93605d6b-a2ba-4d7a-bb51-8acb08e5bd1a",
                            Code2 = "PK",
                            Code3 = "PAK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = "9f6d3e75-cd21-409f-9173-aca90f9b93f3",
                            Code2 = "PW",
                            Code3 = "PLW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = "9feb70b9-80a2-4b12-96ea-62d423af00f0",
                            Code2 = "PS",
                            Code3 = "PSE",
                            Name = "Palestine, State of"
                        },
                        new
                        {
                            Id = "9ef3163e-a0b7-4967-ae61-a87b5b5c19bc",
                            Code2 = "PA",
                            Code3 = "PAN",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = "33084585-3273-46ca-8fc7-b169f03dd1b8",
                            Code2 = "PG",
                            Code3 = "PNG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = "33edd49d-df1c-40c0-a098-4a5c369e23a3",
                            Code2 = "PY",
                            Code3 = "PRY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = "57eedc31-71b7-44bc-aca0-2b3ff9e64361",
                            Code2 = "PE",
                            Code3 = "PER",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = "ec195e19-a5f9-4ab3-a0d7-50174fb14dc8",
                            Code2 = "PH",
                            Code3 = "PHL",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = "dd1095a3-0b66-41ae-a3ba-2f415b7839b2",
                            Code2 = "PN",
                            Code3 = "PCN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = "13e332cd-aa81-410d-b18c-ad95b6b13663",
                            Code2 = "PL",
                            Code3 = "POL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = "5e288331-46de-49f9-a1be-896fb4e5cffa",
                            Code2 = "PT",
                            Code3 = "PRT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = "73a60e18-9dbe-4f74-8353-5c5568e572c8",
                            Code2 = "PR",
                            Code3 = "PRI",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = "bcd0422f-1de7-4e28-aa0f-08df50134a83",
                            Code2 = "QA",
                            Code3 = "QAT",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = "39ab367c-b9e6-46a3-be15-132677ab2ab3",
                            Code2 = "RE",
                            Code3 = "REU",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = "325b9be0-826c-432a-aacc-4a8db883567f",
                            Code2 = "RE",
                            Code3 = "REU",
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = "4b2947f4-4d12-47c3-9d57-a8ba8df11ccb",
                            Code2 = "RO",
                            Code3 = "ROU",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = "f4830d35-f82d-4d0a-889c-7500e6e40973",
                            Code2 = "RU",
                            Code3 = "RUS",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = "e8fe4d7a-f640-4c2f-8de2-dd64552074cb",
                            Code2 = "RU",
                            Code3 = "RUS",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = "5387a1a4-d6ae-43cd-b343-e5f2be6af1ea",
                            Code2 = "RW",
                            Code3 = "RWA",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = "54478e1d-a6b7-4c1c-97c1-4d82ede303f6",
                            Code2 = "BL",
                            Code3 = "BLM",
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = "f370ac01-e25a-460a-b95e-fb4e97180f5c",
                            Code2 = "SH",
                            Code3 = "SHN",
                            Name = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            Id = "906fd092-01ed-40a7-a01e-6f51dd72762d",
                            Code2 = "KN",
                            Code3 = "KNA",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = "3a70a768-03fc-4870-9509-9275ab7110b0",
                            Code2 = "LC",
                            Code3 = "LCA",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = "192f49dc-d414-4c45-9b3c-8d90b3f394ee",
                            Code2 = "MF",
                            Code3 = "MAF",
                            Name = "Saint Martin (French part)"
                        },
                        new
                        {
                            Id = "2355a54e-a7f4-4318-871a-38d6edd75207",
                            Code2 = "PM",
                            Code3 = "SPM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = "b582ecd6-a1cf-427d-8bb8-042e0e0aed87",
                            Code2 = "VC",
                            Code3 = "VCT",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = "7f2d7293-2403-45d6-90c0-509842bc1692",
                            Code2 = "WS",
                            Code3 = "WSM",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = "68b82b62-fbdc-4ba3-8077-db71f2c8a249",
                            Code2 = "SM",
                            Code3 = "SMR",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = "b0d1a2c9-16b7-445d-8dc9-c1c1ec13d561",
                            Code2 = "ST",
                            Code3 = "STP",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = "37e82658-5623-497e-aad4-9a62d8912f3b",
                            Code2 = "SA",
                            Code3 = "SAU",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = "f3bbbf8f-b177-4a1a-94f3-c333a5c11391",
                            Code2 = "SN",
                            Code3 = "SEN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = "0806405a-df0b-45a6-8613-788a1af3c621",
                            Code2 = "RS",
                            Code3 = "SRB",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = "b5a0b813-c87a-48da-a4a6-8230e9e6bd52",
                            Code2 = "RS",
                            Code3 = "SRB",
                            Name = "Serbia (Yugoslavia)"
                        },
                        new
                        {
                            Id = "7990469e-7444-4b2b-8b0c-e5370e088840",
                            Code2 = "SC",
                            Code3 = "SYC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = "023fa312-2e64-448c-a3c3-2f819f15acba",
                            Code2 = "SL",
                            Code3 = "SLE",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = "ed4e10a8-3a3d-4651-9f1a-3d51d07b9ab7",
                            Code2 = "SG",
                            Code3 = "SGP",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = "e9924300-87ab-41ab-a182-7813e3875c4a",
                            Code2 = "SX",
                            Code3 = "SXM",
                            Name = "Sint Maarten (Dutch part)"
                        },
                        new
                        {
                            Id = "0ac58dff-6627-46b3-aea9-b80e90155804",
                            Code2 = "SK",
                            Code3 = "SVK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = "48aaaf32-beb2-4923-9aaa-4c95370b9252",
                            Code2 = "SI",
                            Code3 = "SVN",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = "0e51bcfc-47f4-4488-ac1e-06c6cf4e2b80",
                            Code2 = "SB",
                            Code3 = "SLB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = "d906ae67-c0fe-4f92-b876-a746aaa8bca0",
                            Code2 = "SO",
                            Code3 = "SOM",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = "8e4a3dd7-b653-4c95-b450-b8bddb9d6dad",
                            Code2 = "ZA",
                            Code3 = "ZAF",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = "85f7d9d9-72a0-49eb-9209-0fba3cfbabc3",
                            Code2 = "GS",
                            Code3 = "SGS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = "6ceb040a-7570-421d-b75f-152cdbe20a19",
                            Code2 = "SS",
                            Code3 = "SSD",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = "d1f3c06a-280a-4e36-a6d0-5d80a3c7ac2d",
                            Code2 = "ES",
                            Code3 = "ESP",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = "2e940e72-d23a-48ff-9c3c-811610b1556e",
                            Code2 = "ES",
                            Code3 = "ESP",
                            Name = "España"
                        },
                        new
                        {
                            Id = "92ea4afd-0bd6-4fb4-a984-3ea66497462c",
                            Code2 = "LK",
                            Code3 = "LKA",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = "d56e076c-0143-41b0-868b-4a9dc7e5a062",
                            Code2 = "SD",
                            Code3 = "SDN",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = "87a92f9a-3b31-45a9-8ff5-06f1b063d0a3",
                            Code2 = "SR",
                            Code3 = "SUR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = "29e60779-dd75-4484-b510-81a6ef1575c7",
                            Code2 = "SJ",
                            Code3 = "SJM",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = "c25570bd-0810-4872-9c04-86c0ef0ba2c7",
                            Code2 = "SE",
                            Code3 = "SWE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = "17779450-4593-4630-a455-0c0f84fb703b",
                            Code2 = "CH",
                            Code3 = "CHE",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = "3b2540c5-cc80-48b9-aeb3-d53195ecba11",
                            Code2 = "SY",
                            Code3 = "SYR",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = "355fba98-4348-4988-aae6-e327fa3929ac",
                            Code2 = "SY",
                            Code3 = "SYR",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = "57f0c3c3-673d-49e1-b883-93b08b514c8a",
                            Code2 = "TW",
                            Code3 = "TWN",
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            Id = "cc857da7-5f46-40d7-a3d2-5a0d5f8ae681",
                            Code2 = "TW",
                            Code3 = "TWN",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = "249ce334-dcd5-44af-a83b-9113f5727a09",
                            Code2 = "TJ",
                            Code3 = "TJK",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = "88fccb28-b38e-4093-b2e6-b2790ec01e95",
                            Code2 = "TZ",
                            Code3 = "TZA",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = "9cfd90ea-1001-441c-aa9a-6bfbfc3a1b63",
                            Code2 = "TH",
                            Code3 = "THA",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = "f78fb1e7-1322-4f77-a166-7d78776f35db",
                            Code2 = "TL",
                            Code3 = "TLS",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = "7cb25e94-cbe0-46a4-8f46-b7ae5cd06312",
                            Code2 = "TG",
                            Code3 = "TGO",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = "c82f03a5-bd89-44a3-87a8-41984e723e38",
                            Code2 = "TK",
                            Code3 = "TKL",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = "6bb35bfd-1af5-4d98-a308-0c4824241a47",
                            Code2 = "TO",
                            Code3 = "TON",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = "9cba9cc9-9b55-4407-8158-86c3de455e3c",
                            Code2 = "TT",
                            Code3 = "TTO",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = "c805b9a0-9069-4142-a30f-314582da3b7b",
                            Code2 = "TN",
                            Code3 = "TUN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = "a49e3fb1-f5dd-4ac3-bd2a-586fd3bca53c",
                            Code2 = "TR",
                            Code3 = "TUR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = "847ce96d-7f00-4abb-95f5-8d89887deed8",
                            Code2 = "TM",
                            Code3 = "TKM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = "ca709869-c458-4688-b190-903d7bf65e69",
                            Code2 = "TC",
                            Code3 = "TCA",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = "8b659753-4d5c-42d5-891c-5a52f5f85e64",
                            Code2 = "TV",
                            Code3 = "TUV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = "d19bc0f6-bb76-4816-a27f-85258169e92b",
                            Code2 = "UG",
                            Code3 = "UGA",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = "b93dca51-d727-442d-ad20-f72e435998a8",
                            Code2 = "UA",
                            Code3 = "UKR",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = "ba49c51b-7e06-4539-ad8b-3f8be3bec319",
                            Code2 = "AE",
                            Code3 = "ARE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = "92892d5c-732e-48eb-97fa-f0d95670b66b",
                            Code2 = "GB",
                            Code3 = "GBR",
                            Name = "United Kingdom of Great Britain and Northern Ireland"
                        },
                        new
                        {
                            Id = "ec91b935-16a3-46b9-8d8b-a35720331fd5",
                            Code2 = "GB",
                            Code3 = "GBR",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = "844cd310-c633-4077-a629-af5c23207319",
                            Code2 = "US",
                            Code3 = "USA",
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = "97dcd74c-1d3d-4833-bd22-55a67546d067",
                            Code2 = "US",
                            Code3 = "USA",
                            Name = "United States"
                        },
                        new
                        {
                            Id = "975e01db-ab12-442c-ba1f-3b424265958d",
                            Code2 = "UM",
                            Code3 = "UMI",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = "0e66ebff-f321-4e8e-a9b7-0aa4e59a80c2",
                            Code2 = "UY",
                            Code3 = "URY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = "dc17bfac-fc2d-4f3d-8036-111d9de681f5",
                            Code2 = "UZ",
                            Code3 = "UZB",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = "af4e5c94-b79a-431b-a9e8-23688bbeda03",
                            Code2 = "VU",
                            Code3 = "VUT",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = "31f99f96-c345-4a13-8639-bf716ac9c104",
                            Code2 = "VE",
                            Code3 = "VEN",
                            Name = "Venezuela (Bolivarian Republic of)"
                        },
                        new
                        {
                            Id = "32aa5036-4cbf-472e-97af-201f143b14bf",
                            Code2 = "VE",
                            Code3 = "VEN",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = "b95674d5-f7de-4238-aba9-5ba8d6b0a742",
                            Code2 = "VN",
                            Code3 = "VNM",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = "103da448-ca0a-46f9-8c47-aacc7777c552",
                            Code2 = "VG",
                            Code3 = "VGB",
                            Name = "Virgin Islands (British)"
                        },
                        new
                        {
                            Id = "c30b17c1-5289-49c8-84e2-d3fdd839be1c",
                            Code2 = "VG",
                            Code3 = "VGB",
                            Name = "Virgin Isles (British)"
                        },
                        new
                        {
                            Id = "44bc7a2e-aeeb-45d3-b6da-b2620e75ac9f",
                            Code2 = "VI",
                            Code3 = "VIR",
                            Name = "Virgin Islands (U.S.)"
                        },
                        new
                        {
                            Id = "447b16f1-4894-420c-ba88-b8583ccec770",
                            Code2 = "WF",
                            Code3 = "WLF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = "7adc80bf-e289-4f2f-88fe-f207d8f9feba",
                            Code2 = "EH",
                            Code3 = "ESH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = "2bfa8436-4ad3-4d2f-a4c1-85c990b2e57f",
                            Code2 = "YE",
                            Code3 = "YEM",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = "bc262cbe-39da-455f-9249-e421e0038442",
                            Code2 = "ZM",
                            Code3 = "ZMB",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = "4fa476dd-5ec0-4169-9f74-a9bc1daf6f49",
                            Code2 = "ZW",
                            Code3 = "ZWE",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Route", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Approach")
                        .HasColumnType("ntext");

                    b.Property<string>("ApprovedById")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("ApprovedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<float>("Difficulty")
                        .HasColumnType("real");

                    b.Property<string>("History")
                        .HasColumnType("ntext");

                    b.Property<string>("Info")
                        .HasColumnType("ntext");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("RoutesContainerId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("AreaId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RoutesContainerId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "6401cf99-a0dc-4747-9232-d307b21a360c",
                            Name = "superadmin"
                        });
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.AreasContainer", b =>
                {
                    b.HasBaseType("Climbing.Guide.Api.Domain.Entities.Area");

                    b.HasDiscriminator().HasValue("AreasContainer");

                    b.HasData(
                        new
                        {
                            Id = "20144484-65bf-4c55-9f53-3e41cee9d923",
                            CountryId = "dfa4af2c-d01d-4a8a-825e-793d49a656ac",
                            CreatedById = "6401cf99-a0dc-4747-9232-d307b21a360c",
                            CreatedOn = new DateTime(2019, 11, 26, 13, 8, 57, 684, DateTimeKind.Local).AddTicks(7599),
                            Info = "Prilep info.",
                            Name = "Prilep",
                            Revision = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = "c2fccbf6-4363-4850-ad97-54954812457e",
                            CountryId = "dfa4af2c-d01d-4a8a-825e-793d49a656ac",
                            CreatedById = "6401cf99-a0dc-4747-9232-d307b21a360c",
                            CreatedOn = new DateTime(2019, 11, 26, 13, 8, 57, 688, DateTimeKind.Local).AddTicks(2586),
                            Info = "Treskavets Area info.",
                            Name = "Treskavets",
                            ParentId = "20144484-65bf-4c55-9f53-3e41cee9d923",
                            Revision = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = "64875f09-3072-4dab-9d9f-d7286ce818a9",
                            CountryId = "dfa4af2c-d01d-4a8a-825e-793d49a656ac",
                            CreatedById = "6401cf99-a0dc-4747-9232-d307b21a360c",
                            CreatedOn = new DateTime(2019, 11, 26, 13, 8, 57, 688, DateTimeKind.Local).AddTicks(4308),
                            Info = "Kamena baba info.",
                            Name = "Kamena baba",
                            ParentId = "20144484-65bf-4c55-9f53-3e41cee9d923",
                            Revision = 1,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.RoutesContainer", b =>
                {
                    b.HasBaseType("Climbing.Guide.Api.Domain.Entities.Area");

                    b.HasDiscriminator().HasValue("RoutesContainer");

                    b.HasData(
                        new
                        {
                            Id = "8d7d8b36-489b-4d9a-bd73-a7caa9853356",
                            CountryId = "dfa4af2c-d01d-4a8a-825e-793d49a656ac",
                            CreatedById = "6401cf99-a0dc-4747-9232-d307b21a360c",
                            CreatedOn = new DateTime(2019, 11, 26, 13, 8, 57, 688, DateTimeKind.Local).AddTicks(4199),
                            Info = "Paragliding info.",
                            Name = "Paragliding",
                            ParentId = "c2fccbf6-4363-4850-ad97-54954812457e",
                            Revision = 1,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Area", b =>
                {
                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.AreasContainer", null)
                        .WithMany("Areas")
                        .HasForeignKey("AreasContainerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.Area", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.OwnsOne("Climbing.Guide.Api.Domain.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<string>("AreaId")
                                .HasColumnType("nvarchar(36)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("AreaId");

                            b1.ToTable("Area");

                            b1.WithOwner()
                                .HasForeignKey("AreaId");
                        });
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Country", b =>
                {
                    b.OwnsOne("Climbing.Guide.Api.Domain.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<string>("CountryId")
                                .HasColumnType("nvarchar(36)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("CountryId");

                            b1.ToTable("Countries");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");
                        });
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Route", b =>
                {
                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.RoutesContainer", null)
                        .WithMany("Routes")
                        .HasForeignKey("RoutesContainerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.OwnsOne("Climbing.Guide.Api.Domain.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<string>("RouteId")
                                .HasColumnType("nvarchar(36)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsMany("Climbing.Guide.Api.Domain.Entities.SchemaPoint", "Topo", b1 =>
                        {
                            b1.Property<string>("RouteId")
                                .HasColumnType("nvarchar(36)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.HasKey("RouteId", "Id");

                            b1.ToTable("SchemaPoint");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
