// <auto-generated />
using System;
using Climbing.Guide.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Climbing.Guide.Api.Infrastructure.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20191122110633_LocationMandatory")]
    partial class LocationMandatory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Accomodations")
                        .HasColumnType("ntext");

                    b.Property<string>("Approach")
                        .HasColumnType("ntext");

                    b.Property<string>("ApprovedById")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("ApprovedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("AreasContainerId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descent")
                        .HasColumnType("ntext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ethics")
                        .HasColumnType("ntext");

                    b.Property<string>("History")
                        .HasColumnType("ntext");

                    b.Property<string>("Info")
                        .HasColumnType("ntext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Restrictions")
                        .HasColumnType("ntext");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("AreasContainerId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ParentId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Area");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Area");
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Code2")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Code3")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Route", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Approach")
                        .HasColumnType("ntext");

                    b.Property<string>("ApprovedById")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("ApprovedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<byte[]>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<float>("Difficulty")
                        .HasColumnType("real");

                    b.Property<string>("History")
                        .HasColumnType("ntext");

                    b.Property<string>("Info")
                        .HasColumnType("ntext");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("RoutesContainerId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("AreaId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RoutesContainerId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.AreasContainer", b =>
                {
                    b.HasBaseType("Climbing.Guide.Api.Domain.Entities.Area");

                    b.HasDiscriminator().HasValue("AreasContainer");
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.RoutesContainer", b =>
                {
                    b.HasBaseType("Climbing.Guide.Api.Domain.Entities.Area");

                    b.HasDiscriminator().HasValue("RoutesContainer");
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Area", b =>
                {
                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.AreasContainer", null)
                        .WithMany("Areas")
                        .HasForeignKey("AreasContainerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.Area", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.OwnsOne("Climbing.Guide.Api.Domain.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<string>("AreaId")
                                .HasColumnType("nvarchar(36)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("AreaId");

                            b1.ToTable("Area");

                            b1.WithOwner()
                                .HasForeignKey("AreaId");
                        });
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Country", b =>
                {
                    b.OwnsOne("Climbing.Guide.Api.Domain.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<string>("CountryId")
                                .HasColumnType("nvarchar(36)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("CountryId");

                            b1.ToTable("Countries");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");
                        });
                });

            modelBuilder.Entity("Climbing.Guide.Api.Domain.Entities.Route", b =>
                {
                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.RoutesContainer", null)
                        .WithMany("Routes")
                        .HasForeignKey("RoutesContainerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Climbing.Guide.Api.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.OwnsOne("Climbing.Guide.Api.Domain.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<string>("RouteId")
                                .HasColumnType("nvarchar(36)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("RouteId");

                            b1.ToTable("Routes");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });

                    b.OwnsMany("Climbing.Guide.Api.Domain.Entities.SchemaPoint", "Topo", b1 =>
                        {
                            b1.Property<string>("RouteId")
                                .HasColumnType("nvarchar(36)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.HasKey("RouteId", "Id");

                            b1.ToTable("SchemaPoint");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
