# Generated by Django 2.1.2 on 2018-12-24 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('size', models.FloatField()),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_approved_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AreaTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('approach', models.TextField(blank=True, default='')),
                ('history', models.TextField(blank=True, default='')),
                ('ethics', models.TextField(blank=True, default='')),
                ('accomodations', models.TextField(blank=True, default='')),
                ('restrictions', models.TextField(blank=True, default='')),
                ('descent', models.TextField(blank=True, default='')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='guide_api.Area')),
            ],
            options={
                'verbose_name': 'Area Translation',
                'db_table': 'guide_api_area_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('code_2', models.CharField(default='BG', max_length=2)),
                ('code_3', models.CharField(default='BGR', max_length=3)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('sub_region', models.CharField(blank=True, max_length=100)),
                ('intermediate_region', models.CharField(blank=True, max_length=100)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='guide_api.Country')),
            ],
            options={
                'verbose_name': 'Country Translation',
                'db_table': 'guide_api_country_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('length', models.PositiveSmallIntegerField(blank=True, default='0')),
                ('type', models.SmallIntegerField(choices=[(1, 'Boulder'), (2, 'Sport'), (4, 'Trad')], default=1)),
                ('topo', models.TextField()),
                ('schema', models.ImageField(blank=True, upload_to='images/routes/schema/%Y/%m/%d/')),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_approved_by', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_area', to='guide_api.Area')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_create_by', to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revision_previous', to='guide_api.Route')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RouteTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('approach', models.TextField(blank=True, default='')),
                ('history', models.TextField(blank=True, default='')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='guide_api.Route')),
            ],
            options={
                'verbose_name': 'Route Translation',
                'db_table': 'guide_api_route_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='guide_api.Country'),
        ),
        migrations.AddField(
            model_name='area',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='area_children', to='guide_api.Area'),
        ),
        migrations.AddField(
            model_name='area',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='revision_previous', to='guide_api.Area'),
        ),
        migrations.AlterUniqueTogether(
            name='routetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='countrytranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='areatranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
