# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.PositiveIntegerField(blank=True, default='0')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('size', models.DecimalField(decimal_places=6, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('restrictions', models.TextField(blank=True, default='')),
                ('access', models.TextField(blank=True, default='')),
                ('descent', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_create_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.PositiveIntegerField(blank=True, default='0')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('size', models.DecimalField(decimal_places=6, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('restrictions', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_create_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.PositiveIntegerField(blank=True, default='0')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('length', models.PositiveSmallIntegerField(blank=True, default='0')),
                ('fa', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.SmallIntegerField(choices=[(1, 'Boulder'), (2, 'Sport'), (4, 'Trad')], default=1)),
                ('schema', models.FileField(upload_to='routes/schema/%Y/%m/%d/')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_create_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.PositiveIntegerField(blank=True, default='0')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('size', models.DecimalField(decimal_places=6, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('access', models.TextField(blank=True, default='')),
                ('descent', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_approved_by', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide_api.Area')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_create_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='route',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide_api.Sector'),
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide_api.Region'),
        ),
    ]
