# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('restrictions', models.TextField(blank=True, default='')),
                ('access', models.TextField(blank=True, default='')),
                ('descent', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'area Translation',
                'db_table': 'guide_api_area_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('restrictions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'region Translation',
                'db_table': 'guide_api_region_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RouteTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('fa', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'route Translation',
                'db_table': 'guide_api_route_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SectorTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('access', models.TextField(blank=True, default='')),
                ('descent', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'sector Translation',
                'db_table': 'guide_api_sector_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='area',
            name='access',
        ),
        migrations.RemoveField(
            model_name='area',
            name='descent',
        ),
        migrations.RemoveField(
            model_name='area',
            name='info',
        ),
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
        migrations.RemoveField(
            model_name='area',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='region',
            name='info',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='route',
            name='fa',
        ),
        migrations.RemoveField(
            model_name='route',
            name='info',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='access',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='descent',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='info',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='name',
        ),
        migrations.AddField(
            model_name='sectortranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='guide_api.Sector'),
        ),
        migrations.AddField(
            model_name='routetranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='guide_api.Route'),
        ),
        migrations.AddField(
            model_name='regiontranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='guide_api.Region'),
        ),
        migrations.AddField(
            model_name='areatranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='guide_api.Area'),
        ),
        migrations.AlterUniqueTogether(
            name='sectortranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='routetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='regiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='areatranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
