# Generated by Django 2.1.2 on 2018-12-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='topo',
        ),
    ]
