# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0002_auto_20171118_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='areatranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Area Translation'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='regiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Region Translation'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='routetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Route Translation'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterModelOptions(
            name='sectortranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Sector Translation'},
        ),
        migrations.AddField(
            model_name='route',
            name='schemaThumb',
            field=models.ImageField(default='thumbs/routes/schema/2017/11/18/DSC_0763_aLf7bAT.JPG', upload_to='thumbs/routes/schema/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='schema',
            field=models.ImageField(upload_to='routes/schema/%Y/%m/%d/'),
        ),
    ]
