# Generated by Django 2.1.2 on 2018-12-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0002_remove_route_topo'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='topo',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
