# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0003_auto_20171119_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='schema',
            field=models.ImageField(upload_to='images/routes/schema/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='route',
            name='schemaThumb',
            field=models.ImageField(blank=True, upload_to='images/thumbs/routes/schema/%Y/%m/%d/'),
        ),
    ]
