# Generated by Django 2.1.2 on 2018-11-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0005_auto_20181101_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country_code',
            field=models.CharField(default='un', max_length=10),
        ),
    ]
