# Generated by Django 2.1.2 on 2018-11-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0006_region_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='route',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sector',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
