# Generated by Django 2.1.2 on 2018-11-21 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide_api', '0007_auto_20181121_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
