# Generated by Django 2.1.2 on 2018-11-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0008_region_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='region',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='route',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sector',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
