# Generated by Django 2.1.2 on 2018-11-26 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide_api', '0011_auto_20181121_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
