# Generated by Django 2.1.2 on 2018-11-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0012_area_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='schema',
            field=models.ImageField(blank=True, upload_to='images/routes/schema/%Y/%m/%d/'),
        ),
    ]
