# Generated by Django 2.1.2 on 2018-11-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0013_auto_20181127_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='schemaThumb2048',
        ),
        migrations.RemoveField(
            model_name='route',
            name='schemaThumb256',
        ),
    ]
