# Generated by Django 2.1.2 on 2018-12-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide_api', '0014_auto_20181127_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sector',
            name='size',
            field=models.FloatField(),
        ),
    ]
